using System.Collections.Generic;

namespace ComfyCarry.Services;

/// <summary>
/// 中英双语资源。键名以点号分层。
/// 本实现为内联字典；可后续替换为 .resw 资源文件。
/// </summary>
public sealed class LocalizationService
{
    private readonly SettingsService _settings;
    public string Current => _settings.Data.Language;

    private static readonly Dictionary<string, string> Zh = new()
    {
        ["app.title"] = "ComfyCarry Companion",
        ["nav.cloud"] = "云存储配置",
        ["nav.pull"] = "产物取回",
        ["nav.settings"] = "设置",
        ["tray.show"] = "显示主窗口",
        ["tray.pause"] = "暂停拉取",
        ["tray.resume"] = "继续拉取",
        ["tray.exit"] = "退出",
        ["tray.status.idle"] = "空闲",
        ["tray.status.syncing"] = "正在拉取…",
        ["tray.status.queued"] = "N 个待取",
        ["common.ok"] = "确定",
        ["common.cancel"] = "取消",
        ["common.save"] = "保存",
        ["common.delete"] = "删除",
        ["common.test"] = "测试连接",
        ["common.browse"] = "浏览…",
        ["common.copy"] = "复制内容",
        ["common.export"] = "导出配置文件",
        ["common.openFolder"] = "打开本地文件夹",
        ["common.refresh"] = "刷新",
        ["common.add"] = "添加",
        ["common.edit"] = "编辑",
        ["common.close"] = "关闭",
        ["common.next"] = "下一步",
        ["common.back"] = "上一步",
        ["common.finish"] = "完成",
        ["cloud.title"] = "云存储配置",
        ["cloud.home.intro"] = "在这里添加并配置你的云盘，完成后导出配置即可使用。",
        ["cloud.home.remotes"] = "已配置的云盘",
        ["cloud.home.noRemotes"] = "还没有云盘，点下面的按钮添加一个吧。",
        ["cloud.newRemote"] = "新建云盘",
        ["cloud.step.type"] = "选择云类型",
        ["cloud.step.name"] = "命名",
        ["cloud.step.config"] = "配置",
        ["cloud.step.test"] = "连接测试",
        ["cloud.step.tree"] = "建标准目录（可选）",
        ["cloud.step.export"] = "导出",
        ["cloud.remoteName"] = "名称",
        ["cloud.remoteName.invalid"] = "只能用字母、数字、下划线和减号。",
        ["cloud.remoteName.duplicate"] = "这个名字已经用过了，换一个吧。",
        ["cloud.config.save"] = "保存配置",
        ["cloud.config.authorize"] = "开始授权",
        ["cloud.config.oauthHint"] = "点击后会在浏览器里登录你的账号，完成后自动继续。",
        ["cloud.config.authorizing"] = "正在处理，请稍候…",
        ["cloud.config.browserOpening"] = "正在打开浏览器…",
        ["cloud.config.waitingLogin"] = "浏览器已打开，请在浏览器完成登录…",
        ["cloud.config.authorized"] = "授权完成，可以继续下一步了。",
        ["cloud.config.chooseDrive"] = "请选择一个云盘：",
        ["cloud.config.option"] = "选项",
        ["cloud.config.failed"] = "保存失败，请检查参数。",
        ["cloud.rcloneMissing.title"] = "缺少 rclone.exe",
        ["cloud.rcloneMissing"] = "没有找到 rclone.exe，请重新安装本程序后再试。",
        ["cloud.test.running"] = "正在测试…",
        ["cloud.test.ok"] = "连接成功",
        ["cloud.test.fail"] = "连接失败",
        ["cloud.tree.hint"] = "自动创建常用目录：models、loras、checkpoints、output 等。",
        ["cloud.tree.toggle"] = "创建标准目录",
        ["cloud.tree.run"] = "创建",
        ["cloud.tree.running"] = "正在创建…",
        ["cloud.tree.ok"] = "创建完成",
        ["cloud.tree.partial"] = "部分失败",
        ["cloud.export.guide"] = "导出配置文件后，按面板提示完成云存储设置。",
        ["cloud.export.preview"] = "配置内容",
        ["cloud.export.noConf"] = "还没有生成配置。",
        ["cloud.export.saved"] = "已保存到",
        ["cloud.export.copied"] = "已复制到剪贴板。",
        ["pull.title"] = "产物取回",
        ["pull.intro"] = "把远程实例的产物取回到本机。",
        ["pull.connect"] = "连接实例",
        ["pull.panelUrl"] = "面板 URL",
        ["pull.panelPwd"] = "面板密码",
        ["pull.connect.btn"] = "连接并保存",
        ["pull.rules"] = "拉取规则",
        ["pull.rule.new"] = "新建规则",
        ["pull.rule.localPath"] = "本机目标文件夹",
        ["pull.rule.method"] = "方式",
        ["pull.rule.method.copy"] = "复制（保留远程原文件）",
        ["pull.rule.method.move"] = "移动（取回后删除远程原文件）",
        ["pull.rule.filters"] = "文件类型（扩展名，空格分隔）",
        ["pull.rule.trigger"] = "触发",
        ["pull.rule.trigger.watch"] = "定时",
        ["pull.rule.trigger.manual"] = "手动",
        ["pull.rule.interval"] = "间隔（秒）",
        ["pull.rule.move.confirm"] = "移动方式会在取回后删除远程原文件，确定继续？",
        ["pull.status.idle"] = "空闲",
        ["pull.status.syncing"] = "拉取中",
        ["pull.status.error"] = "错误",
        ["pull.noInstance"] = "尚未连接实例。请先连接，或在设置中添加。",
        ["pull.401"] = "登录已过期，正在重新连接…",
        ["settings.title"] = "设置",
        ["settings.instances"] = "实例管理",
        ["settings.language"] = "语言",
        ["settings.theme"] = "主题",
        ["settings.theme.system"] = "跟随系统",
        ["settings.theme.light"] = "浅色",
        ["settings.theme.dark"] = "深色",
        ["settings.autostart"] = "开机自启",
        ["settings.closeToTray"] = "关闭窗口时最小化到托盘",
        ["settings.proxy"] = "网络代理",
        ["settings.proxy.hint"] = "如需代理请填写，例如 http://127.0.0.1:7890。留空则不使用代理。",
        ["settings.about"] = "关于",
        ["settings.about.version"] = "版本",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["app.title"] = "ComfyCarry Companion",
        ["nav.cloud"] = "Cloud Storage",
        ["nav.pull"] = "Pull Artifacts",
        ["nav.settings"] = "Settings",
        ["tray.show"] = "Show main window",
        ["tray.pause"] = "Pause pulling",
        ["tray.resume"] = "Resume pulling",
        ["tray.exit"] = "Exit",
        ["tray.status.idle"] = "Idle",
        ["tray.status.syncing"] = "Syncing…",
        ["tray.status.queued"] = "N queued",
        ["common.ok"] = "OK",
        ["common.cancel"] = "Cancel",
        ["common.save"] = "Save",
        ["common.delete"] = "Delete",
        ["common.test"] = "Test connection",
        ["common.browse"] = "Browse…",
        ["common.copy"] = "Copy content",
        ["common.export"] = "Export config",
        ["common.openFolder"] = "Open local folder",
        ["common.refresh"] = "Refresh",
        ["common.add"] = "Add",
        ["common.edit"] = "Edit",
        ["common.close"] = "Close",
        ["common.next"] = "Next",
        ["common.back"] = "Back",
        ["common.finish"] = "Finish",
        ["cloud.title"] = "Cloud Storage",
        ["cloud.home.intro"] = "Add and configure your cloud here, then export the config to use it.",
        ["cloud.home.remotes"] = "Configured clouds",
        ["cloud.home.noRemotes"] = "No cloud yet. Tap the button below to add one.",
        ["cloud.newRemote"] = "New cloud",
        ["cloud.step.type"] = "Choose cloud",
        ["cloud.step.name"] = "Name",
        ["cloud.step.config"] = "Configure",
        ["cloud.step.test"] = "Test",
        ["cloud.step.tree"] = "Create folders (optional)",
        ["cloud.step.export"] = "Export",
        ["cloud.remoteName"] = "Name",
        ["cloud.remoteName.invalid"] = "Only letters, numbers, underscore and dash are allowed.",
        ["cloud.remoteName.duplicate"] = "This name is already used. Pick another.",
        ["cloud.config.save"] = "Save config",
        ["cloud.config.authorize"] = "Authorize",
        ["cloud.config.oauthHint"] = "Tap to sign in via your browser; it continues automatically when done.",
        ["cloud.config.authorizing"] = "Working, please wait…",
        ["cloud.config.browserOpening"] = "Opening browser…",
        ["cloud.config.waitingLogin"] = "Browser opened. Please finish signing in there…",
        ["cloud.config.authorized"] = "Authorized. You can continue.",
        ["cloud.config.chooseDrive"] = "Pick a drive:",
        ["cloud.config.option"] = "Option",
        ["cloud.config.failed"] = "Save failed. Please check your input.",
        ["cloud.rcloneMissing.title"] = "rclone.exe missing",
        ["cloud.rcloneMissing"] = "rclone.exe not found. Please reinstall this app and try again.",
        ["cloud.test.running"] = "Testing…",
        ["cloud.test.ok"] = "Connected",
        ["cloud.test.fail"] = "Connection failed",
        ["cloud.tree.hint"] = "Create common folders: models, loras, checkpoints, output, etc.",
        ["cloud.tree.toggle"] = "Create standard folders",
        ["cloud.tree.run"] = "Create",
        ["cloud.tree.running"] = "Creating…",
        ["cloud.tree.ok"] = "Done",
        ["cloud.tree.partial"] = "Partially failed",
        ["cloud.export.guide"] = "Export the config file, then finish cloud setup as your panel guides you.",
        ["cloud.export.preview"] = "Config content",
        ["cloud.export.noConf"] = "No config generated yet.",
        ["cloud.export.saved"] = "Saved to",
        ["cloud.export.copied"] = "Copied to clipboard.",
        ["pull.title"] = "Pull Artifacts",
        ["pull.intro"] = "Pull outputs from your remote instance to this computer.",
        ["pull.connect"] = "Connect instance",
        ["pull.panelUrl"] = "Panel URL",
        ["pull.panelPwd"] = "Panel password",
        ["pull.connect.btn"] = "Connect & save",
        ["pull.rules"] = "Pull rules",
        ["pull.rule.new"] = "New rule",
        ["pull.rule.localPath"] = "Local target folder",
        ["pull.rule.method"] = "Method",
        ["pull.rule.method.copy"] = "Copy (keep remote files)",
        ["pull.rule.method.move"] = "Move (delete remote files after pull)",
        ["pull.rule.filters"] = "File types (extensions, space-separated)",
        ["pull.rule.trigger"] = "Trigger",
        ["pull.rule.trigger.watch"] = "Scheduled",
        ["pull.rule.trigger.manual"] = "Manual",
        ["pull.rule.interval"] = "Interval (sec)",
        ["pull.rule.move.confirm"] = "Move will delete remote files after pulling. Continue?",
        ["pull.status.idle"] = "Idle",
        ["pull.status.syncing"] = "Syncing",
        ["pull.status.error"] = "Error",
        ["pull.noInstance"] = "No instance connected. Connect one, or add it in Settings.",
        ["pull.401"] = "Session expired, reconnecting…",
        ["settings.title"] = "Settings",
        ["settings.instances"] = "Instances",
        ["settings.language"] = "Language",
        ["settings.theme"] = "Theme",
        ["settings.theme.system"] = "Follow system",
        ["settings.theme.light"] = "Light",
        ["settings.theme.dark"] = "Dark",
        ["settings.autostart"] = "Start with Windows",
        ["settings.closeToTray"] = "Minimize to tray on close",
        ["settings.proxy"] = "Network proxy",
        ["settings.proxy.hint"] = "Optional proxy, e.g. http://127.0.0.1:7890. Leave empty for no proxy.",
        ["settings.about"] = "About",
        ["settings.about.version"] = "Version",
    };

    public LocalizationService(SettingsService settings) => _settings = settings;

    public string T(string key)
    {
        var map = _settings.Data.Language == "en-US" ? En : Zh;
        return map.TryGetValue(key, out var v) ? v : key;
    }
}
