using System.Collections.Generic;

namespace ComfyCarry.Services;

/// <summary>
/// 中英双语资源（简中为主，SPEC §3.1）。键名以点号分层。
/// 本实现为内联字典；可后续替换为 .resw 资源文件。
/// </summary>
public sealed class LocalizationService
{
    private readonly SettingsService _settings;
    public string Current => _settings.Data.Language;

    private static readonly Dictionary<string, string> Zh = new()
    {
        ["app.title"] = "ComfyCarry Companion",
        ["nav.cloud"] = "云存储配置",
        ["nav.pull"] = "产物取回",
        ["nav.settings"] = "设置",
        ["tray.show"] = "显示主窗口",
        ["tray.pause"] = "暂停拉取",
        ["tray.resume"] = "继续拉取",
        ["tray.exit"] = "退出",
        ["tray.status.idle"] = "空闲",
        ["tray.status.syncing"] = "正在拉取…",
        ["tray.status.queued"] = "N 个待取",
        ["common.ok"] = "确定",
        ["common.cancel"] = "取消",
        ["common.save"] = "保存",
        ["common.delete"] = "删除",
        ["common.test"] = "测试连接",
        ["common.browse"] = "浏览…",
        ["common.copy"] = "复制内容",
        ["common.export"] = "导出 rclone.conf",
        ["common.openFolder"] = "打开本地文件夹",
        ["common.refresh"] = "刷新",
        ["common.add"] = "添加",
        ["common.edit"] = "编辑",
        ["common.close"] = "关闭",
        ["cloud.title"] = "云存储配置助手",
        ["cloud.intro"] = "纯本地生成 rclone.conf，不连接实例。完成后请上传到面板 Setup Wizard 的『云存储』步骤。",
        ["cloud.step.type"] = "选择云类型",
        ["cloud.step.params"] = "填写参数",
        ["cloud.step.oauth"] = "授权",
        ["cloud.step.test"] = "连接测试",
        ["cloud.step.tree"] = "建标准目录树（可选）",
        ["cloud.step.export"] = "导出配置",
        ["cloud.remoteName"] = "Remote 名称",
        ["cloud.proxy"] = "代理（可选）",
        ["cloud.proxy.hint"] = "形如 http://127.0.0.1:7890，作为 rclone 子进程的 HTTP_PROXY/HTTPS_PROXY。",
        ["cloud.test.running"] = "正在测试…",
        ["cloud.tree.hint"] = "标准目录树：models / loras / checkpoints / output 等（与面板约定一致）。",
        ["cloud.export.guide"] = "打开面板 Setup Wizard 的『云存储』步骤，上传此 rclone.conf 文件。",
        ["cloud.rcloneMissing"] = "未在应用目录找到 rclone.exe。请把 rclone.exe 放到应用目录后再使用本功能。",
        ["pull.title"] = "产物取回",
        ["pull.intro"] = "把实例产物额外拉一份到本机，与你在面板配置的网盘同步互不影响、可并存。",
        ["pull.connect"] = "连接实例",
        ["pull.panelUrl"] = "面板 URL",
        ["pull.panelPwd"] = "面板密码",
        ["pull.connect.btn"] = "连接并保存",
        ["pull.rules"] = "拉取规则",
        ["pull.rule.new"] = "新建规则",
        ["pull.rule.localPath"] = "本机目标文件夹",
        ["pull.rule.method"] = "方式",
        ["pull.rule.method.copy"] = "copy（保留实例源文件）",
        ["pull.rule.method.move"] = "move（拉后清空实例源）",
        ["pull.rule.filters"] = "过滤器（扩展名，空格分隔）",
        ["pull.rule.trigger"] = "触发",
        ["pull.rule.trigger.watch"] = "watch（定时）",
        ["pull.rule.trigger.manual"] = "manual（手动）",
        ["pull.rule.interval"] = "间隔（秒）",
        ["pull.rule.move.confirm"] = "move 会在本机拉取完成后删除实例源文件，确定？",
        ["pull.status.idle"] = "空闲",
        ["pull.status.syncing"] = "拉取中",
        ["pull.status.error"] = "错误",
        ["pull.noInstance"] = "尚未连接任何实例。请在顶部切换或到设置页添加。",
        ["pull.401"] = "凭据失效，正在用密码重新连接…",
        ["settings.title"] = "设置",
        ["settings.instances"] = "实例管理",
        ["settings.language"] = "语言",
        ["settings.theme"] = "主题",
        ["settings.theme.system"] = "跟随系统",
        ["settings.theme.light"] = "浅色",
        ["settings.theme.dark"] = "深色",
        ["settings.autostart"] = "开机自启",
        ["settings.about"] = "关于",
        ["settings.about.version"] = "版本",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["app.title"] = "ComfyCarry Companion",
        ["nav.cloud"] = "Cloud Storage Setup",
        ["nav.pull"] = "Pull Artifacts",
        ["nav.settings"] = "Settings",
        ["tray.show"] = "Show main window",
        ["tray.pause"] = "Pause pulling",
        ["tray.resume"] = "Resume pulling",
        ["tray.exit"] = "Exit",
        ["tray.status.idle"] = "Idle",
        ["tray.status.syncing"] = "Syncing…",
        ["tray.status.queued"] = "N queued",
        ["common.ok"] = "OK",
        ["common.cancel"] = "Cancel",
        ["common.save"] = "Save",
        ["common.delete"] = "Delete",
        ["common.test"] = "Test connection",
        ["common.browse"] = "Browse…",
        ["common.copy"] = "Copy content",
        ["common.export"] = "Export rclone.conf",
        ["common.openFolder"] = "Open local folder",
        ["common.refresh"] = "Refresh",
        ["common.add"] = "Add",
        ["common.edit"] = "Edit",
        ["common.close"] = "Close",
        ["cloud.title"] = "Cloud Storage Setup Helper",
        ["cloud.intro"] = "Generates rclone.conf locally, no instance connection. Upload it to the panel Setup Wizard ‘Cloud Storage’ step.",
        ["cloud.step.type"] = "Choose cloud",
        ["cloud.step.params"] = "Parameters",
        ["cloud.step.oauth"] = "Authorize",
        ["cloud.step.test"] = "Test",
        ["cloud.step.tree"] = "Create folder tree (optional)",
        ["cloud.step.export"] = "Export",
        ["cloud.remoteName"] = "Remote name",
        ["cloud.proxy"] = "Proxy (optional)",
        ["cloud.proxy.hint"] = "e.g. http://127.0.0.1:7890, set as HTTP_PROXY/HTTPS_PROXY for rclone subprocess.",
        ["cloud.test.running"] = "Testing…",
        ["cloud.tree.hint"] = "Standard tree: models / loras / checkpoints / output, etc.",
        ["cloud.export.guide"] = "Open the panel Setup Wizard ‘Cloud Storage’ step and upload this rclone.conf.",
        ["cloud.rcloneMissing"] = "rclone.exe not found in app directory. Please place rclone.exe there before using this feature.",
        ["pull.title"] = "Pull Artifacts",
        ["pull.intro"] = "Pulls a copy of instance outputs to local; coexists with your panel-configured cloud sync, does not interfere.",
        ["pull.connect"] = "Connect instance",
        ["pull.panelUrl"] = "Panel URL",
        ["pull.panelPwd"] = "Panel password",
        ["pull.connect.btn"] = "Connect & save",
        ["pull.rules"] = "Pull rules",
        ["pull.rule.new"] = "New rule",
        ["pull.rule.localPath"] = "Local target folder",
        ["pull.rule.method"] = "Method",
        ["pull.rule.method.copy"] = "copy (keep instance source)",
        ["pull.rule.method.move"] = "move (clear instance source after pull)",
        ["pull.rule.filters"] = "Filters (extensions, space-separated)",
        ["pull.rule.trigger"] = "Trigger",
        ["pull.rule.trigger.watch"] = "watch (scheduled)",
        ["pull.rule.trigger.manual"] = "manual",
        ["pull.rule.interval"] = "Interval (sec)",
        ["pull.rule.move.confirm"] = "move will delete instance source files after local pull completes. Continue?",
        ["pull.status.idle"] = "Idle",
        ["pull.status.syncing"] = "Syncing",
        ["pull.status.error"] = "Error",
        ["pull.noInstance"] = "No instance connected. Switch at top or add one in Settings.",
        ["pull.401"] = "Credentials invalid, reconnecting with password…",
        ["settings.title"] = "Settings",
        ["settings.instances"] = "Instances",
        ["settings.language"] = "Language",
        ["settings.theme"] = "Theme",
        ["settings.theme.system"] = "Follow system",
        ["settings.theme.light"] = "Light",
        ["settings.theme.dark"] = "Dark",
        ["settings.autostart"] = "Start with Windows",
        ["settings.about"] = "About",
        ["settings.about.version"] = "Version",
    };

    public LocalizationService(SettingsService settings) => _settings = settings;

    public string T(string key)
    {
        var map = _settings.Data.Language == "en-US" ? En : Zh;
        return map.TryGetValue(key, out var v) ? v : key;
    }
}
