using System.Collections.Generic;

namespace ComfyCarry.Services;

/// <summary>
/// 中英双语资源。键名以点号分层。
/// 本实现为内联字典；可后续替换为 .resw 资源文件。
/// </summary>
public sealed class LocalizationService
{
    private readonly SettingsService _settings;
    public string Current => _settings.Data.Language;

    private static readonly Dictionary<string, string> Zh = new()
    {
        ["app.title"] = "ComfyCarry Companion",
        ["nav.cloud"] = "云存储配置",
        ["nav.pull"] = "产物取回",
        ["nav.settings"] = "设置",
        ["tray.show"] = "显示主窗口",
        ["tray.pause"] = "暂停拉取",
        ["tray.resume"] = "继续拉取",
        ["tray.exit"] = "退出",
        ["tray.status.idle"] = "空闲",
        ["tray.status.syncing"] = "正在拉取…",
        ["tray.status.queued"] = "N 个待取",
        ["common.ok"] = "确定",
        ["common.cancel"] = "取消",
        ["common.save"] = "保存",
        ["common.delete"] = "删除",
        ["common.test"] = "测试连接",
        ["common.browse"] = "浏览…",
        ["common.copy"] = "复制内容",
        ["common.export"] = "导出 rclone.conf",
        ["common.openFolder"] = "打开本地文件夹",
        ["common.refresh"] = "刷新",
        ["common.add"] = "添加",
        ["common.edit"] = "编辑",
        ["common.close"] = "关闭",
        ["cloud.title"] = "云存储配置",
        ["cloud.intro"] = "在本地配置云盘账号并导出配置，供面板云存储设置使用。",
        ["cloud.step.type"] = "选择云类型",
        ["cloud.step.params"] = "填写参数",
        ["cloud.step.oauth"] = "授权",
        ["cloud.step.test"] = "连接测试",
        ["cloud.step.tree"] = "建标准目录树（可选）",
        ["cloud.step.export"] = "导出配置",
        ["cloud.remoteName"] = "Remote 名称",
        ["cloud.proxy"] = "代理（可选）",
        ["cloud.proxy.hint"] = "如需代理请填写，例如 http://127.0.0.1:7890。",
        ["cloud.test.running"] = "正在测试…",
        ["cloud.tree.hint"] = "创建常用目录：models、loras、checkpoints、output 等。",
        ["cloud.export.guide"] = "导出配置文件后，按面板提示完成云存储设置。",
        ["cloud.rcloneMissing"] = "云存储组件缺失，请重新安装应用后再试。",
        ["pull.title"] = "产物取回",
        ["pull.intro"] = "把远程实例的产物取回到本机。",
        ["pull.connect"] = "连接实例",
        ["pull.panelUrl"] = "面板 URL",
        ["pull.panelPwd"] = "面板密码",
        ["pull.connect.btn"] = "连接并保存",
        ["pull.rules"] = "拉取规则",
        ["pull.rule.new"] = "新建规则",
        ["pull.rule.localPath"] = "本机目标文件夹",
        ["pull.rule.method"] = "方式",
        ["pull.rule.method.copy"] = "复制（保留远程原文件）",
        ["pull.rule.method.move"] = "移动（取回后删除远程原文件）",
        ["pull.rule.filters"] = "文件类型（扩展名，空格分隔）",
        ["pull.rule.trigger"] = "触发",
        ["pull.rule.trigger.watch"] = "定时",
        ["pull.rule.trigger.manual"] = "手动",
        ["pull.rule.interval"] = "间隔（秒）",
        ["pull.rule.move.confirm"] = "移动方式会在取回后删除远程原文件，确定继续？",
        ["pull.status.idle"] = "空闲",
        ["pull.status.syncing"] = "拉取中",
        ["pull.status.error"] = "错误",
        ["pull.noInstance"] = "尚未连接实例。请先连接，或在设置中添加。",
        ["pull.401"] = "登录已过期，正在重新连接…",
        ["settings.title"] = "设置",
        ["settings.instances"] = "实例管理",
        ["settings.language"] = "语言",
        ["settings.theme"] = "主题",
        ["settings.theme.system"] = "跟随系统",
        ["settings.theme.light"] = "浅色",
        ["settings.theme.dark"] = "深色",
        ["settings.autostart"] = "开机自启",
        ["settings.closeToTray"] = "关闭窗口时最小化到托盘",
        ["settings.about"] = "关于",
        ["settings.about.version"] = "版本",
        ["cloud.newRemote"] = "新建 Remote",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["app.title"] = "ComfyCarry Companion",
        ["nav.cloud"] = "Cloud Storage Setup",
        ["nav.pull"] = "Pull Artifacts",
        ["nav.settings"] = "Settings",
        ["tray.show"] = "Show main window",
        ["tray.pause"] = "Pause pulling",
        ["tray.resume"] = "Resume pulling",
        ["tray.exit"] = "Exit",
        ["tray.status.idle"] = "Idle",
        ["tray.status.syncing"] = "Syncing…",
        ["tray.status.queued"] = "N queued",
        ["common.ok"] = "OK",
        ["common.cancel"] = "Cancel",
        ["common.save"] = "Save",
        ["common.delete"] = "Delete",
        ["common.test"] = "Test connection",
        ["common.browse"] = "Browse…",
        ["common.copy"] = "Copy content",
        ["common.export"] = "Export rclone.conf",
        ["common.openFolder"] = "Open local folder",
        ["common.refresh"] = "Refresh",
        ["common.add"] = "Add",
        ["common.edit"] = "Edit",
        ["common.close"] = "Close",
        ["cloud.title"] = "Cloud Storage Setup",
        ["cloud.intro"] = "Configure your cloud account locally and export the config for your panel's cloud storage.",
        ["cloud.step.type"] = "Choose cloud",
        ["cloud.step.params"] = "Parameters",
        ["cloud.step.oauth"] = "Authorize",
        ["cloud.step.test"] = "Test",
        ["cloud.step.tree"] = "Create folder tree (optional)",
        ["cloud.step.export"] = "Export",
        ["cloud.remoteName"] = "Remote name",
        ["cloud.proxy"] = "Proxy (optional)",
        ["cloud.proxy.hint"] = "Optional proxy, e.g. http://127.0.0.1:7890.",
        ["cloud.test.running"] = "Testing…",
        ["cloud.tree.hint"] = "Create common folders: models, loras, checkpoints, output, etc.",
        ["cloud.export.guide"] = "Export the config file, then finish cloud setup as your panel guides you.",
        ["cloud.rcloneMissing"] = "Cloud storage component is missing. Please reinstall the app and try again.",
        ["pull.title"] = "Pull Artifacts",
        ["pull.intro"] = "Pull outputs from your remote instance to this computer.",
        ["pull.connect"] = "Connect instance",
        ["pull.panelUrl"] = "Panel URL",
        ["pull.panelPwd"] = "Panel password",
        ["pull.connect.btn"] = "Connect & save",
        ["pull.rules"] = "Pull rules",
        ["pull.rule.new"] = "New rule",
        ["pull.rule.localPath"] = "Local target folder",
        ["pull.rule.method"] = "Method",
        ["pull.rule.method.copy"] = "Copy (keep remote files)",
        ["pull.rule.method.move"] = "Move (delete remote files after pull)",
        ["pull.rule.filters"] = "File types (extensions, space-separated)",
        ["pull.rule.trigger"] = "Trigger",
        ["pull.rule.trigger.watch"] = "Scheduled",
        ["pull.rule.trigger.manual"] = "Manual",
        ["pull.rule.interval"] = "Interval (sec)",
        ["pull.rule.move.confirm"] = "Move will delete remote files after pulling. Continue?",
        ["pull.status.idle"] = "Idle",
        ["pull.status.syncing"] = "Syncing",
        ["pull.status.error"] = "Error",
        ["pull.noInstance"] = "No instance connected. Connect one, or add it in Settings.",
        ["pull.401"] = "Session expired, reconnecting…",
        ["settings.title"] = "Settings",
        ["settings.instances"] = "Instances",
        ["settings.language"] = "Language",
        ["settings.theme"] = "Theme",
        ["settings.theme.system"] = "Follow system",
        ["settings.theme.light"] = "Light",
        ["settings.theme.dark"] = "Dark",
        ["settings.autostart"] = "Start with Windows",
        ["settings.closeToTray"] = "Minimize to tray on close",
        ["settings.about"] = "About",
        ["settings.about.version"] = "Version",
        ["cloud.newRemote"] = "New remote",
    };

    public LocalizationService(SettingsService settings) => _settings = settings;

    public string T(string key)
    {
        var map = _settings.Data.Language == "en-US" ? En : Zh;
        return map.TryGetValue(key, out var v) ? v : key;
    }
}
